<a href="https://colab.research.google.com/github/Jahnavi-1218/NASSCOM17/blob/main/smart_crop_health.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np
import pandas as pd
df=pd.DataFrame({
    'day':[1,2,3,4,5,6],
    'soil moisture':[72,68,62,55,48,40],
    'Temperature':[27,29,31,33,35,37],
    'humidity':[78,74,70,65,60,55],
    'nitrogen':[48,46,43,39,35,30],
    'crop health':[94,90,84,76,65,52]
    })
df



,day,soil moisture,Temperature,humidity,nitrogen,crop health
0,1,72,27,78,48,94
1,2,68,29,74,46,90
2,3,62,31,70,43,84
3,4,55,33,65,39,76
4,5,48,35,60,35,65
5,6,40,37,55,30,52


In [34]:
d=df.copy()
for i in d:
    print(d[i])


0    1
1    2
2    3
3    4
4    5
5    6
Name: day, dtype: int64
0    72
1    68
2    62
3    55
4    48
5    40
Name: soil moisture, dtype: int64
0    27
1    29
2    31
3    33
4    35
5    37
Name: Temperature, dtype: int64
0    78
1    74
2    70
3    65
4    60
5    55
Name: humidity, dtype: int64
0    48
1    46
2    43
3    39
4    35
5    30
Name: nitrogen, dtype: int64
0    94
1    90
2    84
3    76
4    65
5    52
Name: crop health, dtype: int64


In [35]:
d["status"]=np.where(
    d['soil moisture']<50,'low soil moisture alert','soil moisture normal'
)
print(d[['soil moisture','status']])

   soil moisture                   status
0             72     soil moisture normal
1             68     soil moisture normal
2             62     soil moisture normal
3             55     soil moisture normal
4             48  low soil moisture alert
5             40  low soil moisture alert


In [36]:
d['condition']=np.where(
    d['Temperature']>35,'high temperature alert','normal temperature'
)
print(d[['Temperature','condition']])

   Temperature               condition
0           27      normal temperature
1           29      normal temperature
2           31      normal temperature
3           33      normal temperature
4           35      normal temperature
5           37  high temperature alert


In [37]:
def crop_status(score):
  if score>80:
     return 'healthy'
  elif score>=50 and score<=80:
    return 'under stress'
  else:
    return 'critical'
d['status']=d['crop health'].apply(crop_status)
print(d[['crop health','status']])



   crop health        status
0           94       healthy
1           90       healthy
2           84       healthy
3           76  under stress
4           65  under stress
5           52  under stress


In [41]:
a=df.copy()

arr=np.array(a)
print(arr)


[[ 1 72 27 78 48 94]
 [ 2 68 29 74 46 90]
 [ 3 62 31 70 43 84]
 [ 4 55 33 65 39 76]
 [ 5 48 35 60 35 65]
 [ 6 40 37 55 30 52]]


In [42]:
print(arr.shape)
rows,columns=arr.shape
print('rows:',rows)
print('columns:',columns)

(6, 6)
rows: 6
columns: 6


In [43]:
avg=np.mean(arr,axis=0)
print(avg)

[ 3.5        57.5        32.         67.         40.16666667 76.83333333]
